[Bot]
Token = ""
HelloText = "Welcome!"
SessionClearText = "Session cleared!"
LimiterText = "Limit 3 requests per 1 minute (%v seconds remaining)"
ThinkingText = "Thinking..."

[ChatGPT]
ApiKey = ""
MaxTokens = 1024
Temperature = 0.9

[Session]
TokensLimit = 1024
Exp = 10

[Limiter]
Tokens = 3
Interval = 1